name: icrl
channels:
  - conda-forge
  - http://conda.anaconda.org/gurobi
dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib
  - gurobi
  - gym
  - tikzplotlib
  - pip
  - pip:
    - gym-minigrid
    - stable-baselines3
    - mlagents==0.27.0
    - gym-unity
    - cvxpy